/* global __dirname */
// Scans library/ for design packs and writes src/library/generated.ts.
// Metro needs every asset require() spelled out at build time, so packs are
// discovered here instead of being listed by hand.
//
//   node scripts/build-library.cjs          regenerate
//   node scripts/build-library.cjs --check  exit 1 if the generated file is stale or a pack is invalid

const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const libraryDir = path.join(root, "library");
const outputFile = path.join(root, "src", "library", "generated.ts");
const backgroundKinds = ["solid", "gradient", "pattern", "illustration", "photo-texture"];
const idPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function isUnit(value) {
  return typeof value === "number" && value >= 0 && value <= 1;
}

function isStringArray(value) {
  return Array.isArray(value) && value.every((item) => typeof item === "string");
}

function readBackgroundPack(packDir, errors) {
  const folder = path.basename(packDir);
  const manifestPath = path.join(packDir, "manifest.json");
  const where = `library/backgrounds/${folder}`;
  if (!fs.existsSync(manifestPath)) {
    errors.push(`${where}: missing manifest.json`);
    return undefined;
  }
  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  } catch (error) {
    errors.push(`${where}/manifest.json: invalid JSON (${error.message})`);
    return undefined;
  }
  if (manifest.id !== folder) errors.push(`${where}: manifest id "${manifest.id}" must match the folder name`);
  if (typeof manifest.label !== "string" || !manifest.label) errors.push(`${where}: label is required`);
  if (manifest.order !== undefined && typeof manifest.order !== "number") errors.push(`${where}: order must be a number`);
  if (!Array.isArray(manifest.backgrounds) || manifest.backgrounds.length === 0) {
    errors.push(`${where}: backgrounds must be a non-empty array`);
    return undefined;
  }
  const items = [];
  for (const [index, item] of manifest.backgrounds.entries()) {
    const at = `${where} backgrounds[${index}]${item && item.id ? ` (${item.id})` : ""}`;
    if (!item || typeof item !== "object") {
      errors.push(`${at}: must be an object`);
      continue;
    }
    if (typeof item.id !== "string" || !idPattern.test(item.id)) errors.push(`${at}: id must be lowercase-kebab-case`);
    if (typeof item.label !== "string" || !item.label) errors.push(`${at}: label is required`);
    if (!backgroundKinds.includes(item.kind)) errors.push(`${at}: kind must be one of ${backgroundKinds.join(", ")}`);
    if (typeof item.backgroundColor !== "string") errors.push(`${at}: backgroundColor is required`);
    if (typeof item.textColor !== "string") errors.push(`${at}: textColor is required`);
    if (!isStringArray(item.palette)) errors.push(`${at}: palette must be a list of colors`);
    if (!isStringArray(item.tags)) errors.push(`${at}: tags must be a list of strings`);
    const area = item.safeArea;
    if (!area || ![area.x, area.y, area.width, area.height].every(isUnit)) {
      errors.push(`${at}: safeArea needs x, y, width, height between 0 and 1`);
    }
    if (item.asset !== undefined) {
      const assetPath = path.join(packDir, item.asset);
      if (typeof item.asset !== "string" || !fs.existsSync(assetPath)) {
        errors.push(`${at}: asset file "${item.asset}" not found`);
      } else if (!assetPath.startsWith(packDir + path.sep)) {
        errors.push(`${at}: asset must be inside the pack folder`);
      }
    }
    items.push(item);
  }
  return { folder, manifest, items };
}

function collectBackgroundPacks(errors) {
  const dir = path.join(libraryDir, "backgrounds");
  if (!fs.existsSync(dir)) return [];
  const packs = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith(".") && !entry.name.startsWith("_"))
    .map((entry) => readBackgroundPack(path.join(dir, entry.name), errors))
    .filter(Boolean);

  const seen = new Map();
  for (const pack of packs) {
    for (const item of pack.items) {
      if (seen.has(item.id)) errors.push(`duplicate background id "${item.id}" in ${seen.get(item.id)} and ${pack.folder}`);
      seen.set(item.id, pack.folder);
    }
  }
  // Packs with an explicit order come first; the rest follow alphabetically.
  return packs.sort((a, b) => {
    const orderA = a.manifest.order ?? Number.POSITIVE_INFINITY;
    const orderB = b.manifest.order ?? Number.POSITIVE_INFINITY;
    return orderA - orderB || a.folder.localeCompare(b.folder);
  });
}

function render(backgroundPacks) {
  const lines = [
    "// Generated by scripts/build-library.cjs from the library/ folder. Do not edit.",
    "// Add or change packs in library/ and run `npm run library`.",
    "",
    "export type GeneratedPack = {",
    "  manifest: unknown;",
    "  sources: Record<string, number>;",
    "};",
    "",
    "export const backgroundPackSources: GeneratedPack[] = ["
  ];
  for (const pack of backgroundPacks) {
    const base = `../../library/backgrounds/${pack.folder}`;
    lines.push("  {");
    lines.push(`    manifest: require("${base}/manifest.json"),`);
    const withAssets = pack.items.filter((item) => typeof item.asset === "string");
    if (withAssets.length === 0) {
      lines.push("    sources: {}");
    } else {
      lines.push("    sources: {");
      withAssets.forEach((item, index) => {
        const asset = item.asset.replace(/\\/g, "/").replace(/^\.\//, "");
        const comma = index < withAssets.length - 1 ? "," : "";
        lines.push(`      "${item.id}": require("${base}/${asset}")${comma}`);
      });
      lines.push("    }");
    }
    lines.push(`  }${pack === backgroundPacks[backgroundPacks.length - 1] ? "" : ","}`);
  }
  lines.push("];", "");
  return lines.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const errors = [];
  const backgroundPacks = collectBackgroundPacks(errors);
  if (errors.length) {
    console.error(`Design library has ${errors.length} problem(s):\n  - ${errors.join("\n  - ")}`);
    process.exit(1);
  }
  const output = render(backgroundPacks);
  const current = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, "utf8").replace(/\r\n/g, "\n") : "";
  if (check) {
    if (current !== output) {
      console.error("src/library/generated.ts is out of date. Run `npm run library`.");
      process.exit(1);
    }
    return;
  }
  if (current !== output) {
    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, output);
  }
  const count = backgroundPacks.reduce((sum, pack) => sum + pack.items.length, 0);
  console.log(`Design library: ${backgroundPacks.length} background packs, ${count} backgrounds.`);
}

main();
